# Site settings
# theme: jekyll-theme-minimal
show_downloads: true
title: Mingyu Choo's Github page!
description: feel free to bookmark this to keep an eye on my project updates.
url: https://mingyuchoo.github.io

# Author
author:
  name: Mingyu Choo
  url: https://mingyuchoo.github.io
  email: mingyuchoo@gmail.com
